apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: nginx-deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: matas-nginx-deployment
- path: apache-deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: matas-apache-deployment
