apiVersion: apps/v1
kind: Deployment
metadata:
  name: matas-nginx-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: matas-nginx-container
        resources:
          requests:
            cpu: "100m"
